package com.koadernoa.app.objektuak.audit.entitateak;

public enum AuditEkintza {
    PROGRAMAZIOA_INPORTATU,
    AURREKO_URTEKO_DENBORALIZAZIOA_INPORTATU,
    UDA_SORTU,
    UDA_EZABATU,
    UDAN_JARDUERA_PLANIFIKATU,
    UDAN_JARDUERA_EZABATU,
    EBALUAZIOA_EDITATU,
    EBALUAKETA_BERRIA,
    UDA_DENBORALIZAZIORA_BOLKATU,
    PROGRAMAZIOA_DENBORALIZAZIORA_BOLKATU,
    JARDUERA_SORTU,
    JARDUERA_MUGITU,
    JARDUERA_EDITATU,
    ASISTENTZIA_PASATU,
    FALTAK_HEZKUNTZATIK_INPORTATU,
    FALTEN_JAKINARAZPENA_DESKARGATU,
    NOTAK_GORDE,
    ESTATISTIKA_BERKALKULATU,
    KOADERNOA_SORTU,
    ORDUTEGI_BERRIA_SORTU,
    KOADERNOA_PARTEKATU
}
