CREATE DATABASE ethazi_migration_test CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE ethazi_migration_test;
CREATE TABLE moduloa(id BIGINT PRIMARY KEY, eei_kodea VARCHAR(255), hizkuntza VARCHAR(20));
CREATE TABLE ikaskuntza_emaitza(id BIGINT PRIMARY KEY AUTO_INCREMENT, moduloa_id BIGINT NOT NULL, ordena INT NOT NULL, kodea VARCHAR(20), deskribapena TEXT NOT NULL, FOREIGN KEY(moduloa_id) REFERENCES moduloa(id));
CREATE TABLE ethazi_lorpen_adierazlea(id BIGINT PRIMARY KEY, deskribapena TEXT);
CREATE TABLE ethazi_gaitasuna(id BIGINT PRIMARY KEY, deskribapena TEXT);
CREATE TABLE ethazi_gaitasun_maila(id BIGINT PRIMARY KEY, deskribapena TEXT);
CREATE TABLE ethazi_mailakatze_eredua(id BIGINT PRIMARY KEY, izena VARCHAR(150));
CREATE TABLE ethazi_mailakatze_maila(id BIGINT PRIMARY KEY, izena VARCHAR(100));
CREATE TABLE ethazi_lorpen_adierazlea_ikaskuntza_emaitza(lorpen_adierazlea_id BIGINT, ikaskuntza_emaitza_id BIGINT, UNIQUE(lorpen_adierazlea_id,ikaskuntza_emaitza_id), FOREIGN KEY(ikaskuntza_emaitza_id) REFERENCES ikaskuntza_emaitza(id));
CREATE TABLE ethazi_kiniela_pisua(adierazlea_id BIGINT, emaitza_id BIGINT, pisua DECIMAL(5,2), PRIMARY KEY(adierazlea_id,emaitza_id), FOREIGN KEY(emaitza_id) REFERENCES ikaskuntza_emaitza(id));
CREATE TABLE ethazi_kiniela_lotura(id BIGINT PRIMARY KEY AUTO_INCREMENT, adierazlea_id BIGINT, emaitza_id BIGINT, oharra TEXT, CONSTRAINT old_pair UNIQUE(adierazlea_id,emaitza_id), FOREIGN KEY(adierazlea_id) REFERENCES ethazi_lorpen_adierazlea(id), FOREIGN KEY(emaitza_id) REFERENCES ikaskuntza_emaitza(id));
CREATE TABLE ethazi_kiniela_lotura_erronka(lotura_id BIGINT, erronka_id BIGINT, FOREIGN KEY(lotura_id) REFERENCES ethazi_kiniela_lotura(id));
INSERT INTO moduloa VALUES(1,'0423','EUSKARA'),(2,'0423','ERDERA'),(3,'0423','INGELERA');
INSERT INTO ikaskuntza_emaitza VALUES(10,1,1,'IE1','EU testua'),(20,2,1,'RA1','ES texto'),(30,3,1,'LO1','EN text');
INSERT INTO ethazi_lorpen_adierazlea VALUES(1,'Adierazlea');
INSERT INTO ethazi_lorpen_adierazlea_ikaskuntza_emaitza VALUES(1,10),(1,20),(1,30);
INSERT INTO ethazi_kiniela_pisua VALUES(1,10,50),(1,20,50),(1,30,50);
INSERT INTO ethazi_kiniela_lotura VALUES(1,1,10,'EU oharra'),(2,1,20,'ES nota'),(3,1,30,'EN note');
INSERT INTO ethazi_kiniela_lotura_erronka VALUES(1,100),(2,200),(3,300);
